/**
 * @file src/platform/linux/kwin_virtual_output.cpp
 * @brief A new screen from KWin for Host Virtual Display.
 */

#include "kwin_virtual_output.h"

#include "kwingrab.h"
#include "virtual_display.h"

#include "src/logging.h"

#include <algorithm>
#include <atomic>
#include <cerrno>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <gio/gio.h>
#include <sys/stat.h>
#include <map>
#include <memory>
#include <mutex>
#include <poll.h>
#include <set>
#include <string_view>
#include <sys/eventfd.h>
#include <thread>
#include <unistd.h>
#include <wayland-client.h>

// Generated by cmake GEN_WAYLAND from src/platform/linux/protocols/
#include "zkde-screencast-unstable-v1.h"

using namespace std::literals;

namespace kwin_virtual_output {
  namespace {
    constexpr auto stream_deadline = 5s;
    // KWin reads the permission entry when a client connects, so a probe that
    // just wrote it tries again for this long.
    constexpr auto permission_retry_budget = 3s;
    constexpr auto permission_retry_step = 250ms;
    constexpr auto stable_absence = 500ms;
    constexpr const char *output_description = "Polaris Host Virtual Display";

    struct output_t {
      wl_output *handle = nullptr;
      std::uint32_t global = 0;
      std::string name;
      int width = 0;
      int height = 0;
    };

    /**
     * One Wayland connection and the registry state this module reads. Used by
     * one thread at a time: the caller while it sets things up, then an
     * anchor's reader thread.
     */
    class connection_t {
    public:
      explicit connection_t(bool bind_screencast):
          bind_screencast_ {bind_screencast} {
      }

      connection_t(const connection_t &) = delete;
      connection_t &operator=(const connection_t &) = delete;

      ~connection_t() {
        if (screencast) {
          zkde_screencast_unstable_v1_destroy(screencast);
        }
        for (auto &output : outputs) {
          // Release, not destroy: from version 3 only release frees the
          // compositor's side too, and the anchor's connection lives long.
          wl_output_release(output->handle);
        }
        outputs.clear();
        if (registry) {
          wl_registry_destroy(registry);
        }
        if (display) {
          wl_display_disconnect(display);
        }
      }

      bool open() {
        const char *wl_name = std::getenv("WAYLAND_DISPLAY");
        if (!wl_name || !*wl_name) {
          return false;
        }
        display = wl_display_connect(wl_name);
        if (!display) {
          return false;
        }
        registry = wl_display_get_registry(display);
        wl_registry_add_listener(registry, &registry_listener, this);
        // The first roundtrip announces the globals, the second delivers each
        // output's name and mode.
        return wl_display_roundtrip(display) >= 0 && wl_display_roundtrip(display) >= 0;
      }

      /** Wait up to `timeout` for events and dispatch them. False when the connection broke. */
      bool pump(std::chrono::milliseconds timeout) {
        if (wl_display_flush(display) < 0 && errno != EAGAIN) {
          return false;
        }
        pollfd fd {wl_display_get_fd(display), POLLIN, 0};
        const int ready = poll(&fd, 1, static_cast<int>(timeout.count()));
        if (ready < 0) {
          return errno == EINTR;
        }
        if (ready > 0) {
          if (fd.revents & (POLLERR | POLLHUP)) {
            return false;
          }
          return wl_display_dispatch(display) >= 0;
        }
        return wl_display_dispatch_pending(display) >= 0;
      }

      const output_t *find(std::string_view name) const {
        for (const auto &output : outputs) {
          if (output->name == name) {
            return output.get();
          }
        }
        return nullptr;
      }

      std::vector<std::string> names() const {
        std::vector<std::string> result;
        for (const auto &output : outputs) {
          if (!output->name.empty()) {
            result.push_back(output->name);
          }
        }
        return result;
      }

      std::set<std::uint32_t> output_globals() const {
        std::set<std::uint32_t> result;
        for (const auto &output : outputs) {
          result.insert(output->global);
        }
        return result;
      }

      wl_display *display = nullptr;
      wl_registry *registry = nullptr;
      zkde_screencast_unstable_v1 *screencast = nullptr;
      std::uint32_t screencast_version = 0;  ///< Offered by KWin, whether or not it was bound
      std::vector<std::unique_ptr<output_t>> outputs;

    private:
      bool bind_screencast_;

      static void on_global(void *data, wl_registry *registry, std::uint32_t name, const char *interface, std::uint32_t version) {
        auto *self = static_cast<connection_t *>(data);
        if (!std::strcmp(interface, zkde_screencast_unstable_v1_interface.name)) {
          self->screencast_version = version;
          if (self->bind_screencast_ && !self->screencast) {
            self->screencast = static_cast<zkde_screencast_unstable_v1 *>(
              wl_registry_bind(registry, name, &zkde_screencast_unstable_v1_interface, std::min(version, 6u))
            );
          }
        } else if (!std::strcmp(interface, wl_output_interface.name) && version >= 4) {
          // Version 4 carries the output's name, which is how the new output is proven.
          auto output = std::make_unique<output_t>();
          output->global = name;
          output->handle = static_cast<wl_output *>(wl_registry_bind(registry, name, &wl_output_interface, 4));
          wl_output_add_listener(output->handle, &output_listener, output.get());
          self->outputs.push_back(std::move(output));
        }
      }

      static void on_global_remove(void *data, wl_registry *, std::uint32_t name) {
        auto *self = static_cast<connection_t *>(data);
        std::erase_if(self->outputs, [&](const std::unique_ptr<output_t> &output) {
          if (output->global != name) {
            return false;
          }
          wl_output_release(output->handle);
          return true;
        });
      }

      static constexpr wl_registry_listener registry_listener = {
        .global = on_global,
        .global_remove = on_global_remove,
      };

      static void on_geometry(void *, wl_output *, std::int32_t, std::int32_t, std::int32_t, std::int32_t, std::int32_t, const char *, const char *, std::int32_t) {
      }

      static void on_mode(void *data, wl_output *, std::uint32_t flags, std::int32_t width, std::int32_t height, std::int32_t) {
        if (flags & WL_OUTPUT_MODE_CURRENT) {
          auto *output = static_cast<output_t *>(data);
          output->width = width;
          output->height = height;
        }
      }

      static void on_done(void *, wl_output *) {
      }

      static void on_scale(void *, wl_output *, std::int32_t) {
      }

      static void on_name(void *data, wl_output *, const char *name) {
        if (name) {
          static_cast<output_t *>(data)->name = name;
        }
      }

      static void on_description(void *, wl_output *, const char *) {
      }

      static constexpr wl_output_listener output_listener = {
        .geometry = on_geometry,
        .mode = on_mode,
        .done = on_done,
        .scale = on_scale,
        .name = on_name,
        .description = on_description,
      };
    };

    /**
     * The stream KWin tied a virtual output to, and a thread that keeps its
     * connection read. An unread connection eventually fills its socket, KWin
     * disconnects the client, and the screen disappears mid-game.
     */
    class anchor_t {
    public:
      anchor_t() = default;
      anchor_t(const anchor_t &) = delete;
      anchor_t &operator=(const anchor_t &) = delete;

      ~anchor_t() {
        stop_reader();
        close_stream();
      }

      /** Start reading the connection. The connection is the reader's alone from here on. */
      bool start_reader() {
        stop_fd_ = eventfd(0, EFD_CLOEXEC | EFD_NONBLOCK);
        if (stop_fd_ < 0) {
          return false;
        }
        reader_ = std::thread {[this] {
          read_loop();
        }};
        return true;
      }

      void stop_reader() {
        if (reader_.joinable()) {
          const std::uint64_t one = 1;
          if (write(stop_fd_, &one, sizeof(one)) < 0) {
            BOOST_LOG(warning) << "KWin virtual output: could not signal the reader thread to stop"sv;
          }
          reader_.join();
        }
        if (stop_fd_ >= 0) {
          close(stop_fd_);
          stop_fd_ = -1;
        }
      }

      void close_stream() {
        if (stream) {
          zkde_screencast_stream_unstable_v1_close(stream);
          stream = nullptr;
          if (connection && connection->display) {
            wl_display_flush(connection->display);
          }
        }
      }

      std::unique_ptr<connection_t> connection;
      zkde_screencast_stream_unstable_v1 *stream = nullptr;
      std::string output_name;
      // Set by callbacks, read from any thread.
      std::atomic<bool> created {false};
      std::atomic<bool> failed {false};
      std::atomic<bool> closed {false};
      std::atomic<bool> dead {false};
      // Written by the failed callback; read only by the thread that dispatches.
      std::string failure;

    private:
      int stop_fd_ = -1;
      std::thread reader_;

      void read_loop() {
        auto *display = connection->display;
        const auto give_up = [&](std::string_view why) {
          dead = true;
          BOOST_LOG(warning) << "KWin virtual output: lost the connection holding ["sv << output_name << "]: "sv << why;
        };
        while (true) {
          while (wl_display_prepare_read(display) != 0) {
            if (wl_display_dispatch_pending(display) < 0) {
              give_up("dispatch failed"sv);
              return;
            }
          }
          if (wl_display_flush(display) < 0 && errno != EAGAIN) {
            wl_display_cancel_read(display);
            give_up("flush failed"sv);
            return;
          }
          pollfd fds[2] {
            {wl_display_get_fd(display), POLLIN, 0},
            {stop_fd_, POLLIN, 0},
          };
          const int ready = poll(fds, 2, -1);
          if (ready < 0) {
            wl_display_cancel_read(display);
            if (errno == EINTR) {
              continue;
            }
            give_up("poll failed"sv);
            return;
          }
          if (fds[1].revents & POLLIN) {
            wl_display_cancel_read(display);
            return;
          }
          if (fds[0].revents & (POLLERR | POLLHUP)) {
            wl_display_cancel_read(display);
            give_up("KWin closed the connection"sv);
            return;
          }
          if (fds[0].revents & POLLIN) {
            if (wl_display_read_events(display) < 0) {
              give_up("read failed"sv);
              return;
            }
          } else {
            wl_display_cancel_read(display);
          }
          if (wl_display_dispatch_pending(display) < 0) {
            give_up("dispatch failed"sv);
            return;
          }
        }
      }

      static void on_closed(void *data, zkde_screencast_stream_unstable_v1 *) {
        // The output stays until the stream is closed from this side or the
        // connection ends, so a closed stream (a PipeWire restart, say) is a
        // degraded anchor, not a removed screen.
        static_cast<anchor_t *>(data)->closed = true;
      }

      static void on_created(void *data, zkde_screencast_stream_unstable_v1 *, std::uint32_t) {
        static_cast<anchor_t *>(data)->created = true;
      }

      static void on_failed(void *data, zkde_screencast_stream_unstable_v1 *, const char *error) {
        auto *self = static_cast<anchor_t *>(data);
        self->failure = error ? error : "unknown";
        self->failed = true;
      }

      static void on_serial(void *data, zkde_screencast_stream_unstable_v1 *, std::uint32_t, std::uint32_t) {
        // Sent before `created` from version 6, which deprecates `created`.
        static_cast<anchor_t *>(data)->created = true;
      }

    public:
      static constexpr zkde_screencast_stream_unstable_v1_listener stream_listener = {
        .closed = on_closed,
        .created = on_created,
        .failed = on_failed,
        .serial = on_serial,
      };
    };

    std::mutex anchors_mutex;
    std::map<std::string, std::unique_ptr<anchor_t>> anchors;  // by output name, guarded by anchors_mutex

    /**
     * Connect, trying again for a few seconds when the permission entry was
     * only just written and KWin has not offered the protocol yet.
     */
    std::unique_ptr<connection_t> connect(bool bind_screencast, bool permission_just_written) {
      const auto give_up_at = std::chrono::steady_clock::now() + permission_retry_budget;
      while (true) {
        auto connection = std::make_unique<connection_t>(bind_screencast);
        if (!connection->open()) {
          return nullptr;
        }
        if (connection->screencast_version != 0 || !permission_just_written ||
            std::chrono::steady_clock::now() >= give_up_at) {
          return connection;
        }
        std::this_thread::sleep_for(permission_retry_step);
      }
    }

    std::string missing_protocol_reason(kwingrab::permission_e permission) {
      if (permission == kwingrab::permission_e::failed) {
        return "KWin does not offer its screencast protocol to Polaris, and the permission entry KWin needs "
               "(a desktop file with X-KDE-Wayland-Interfaces=zkde_screencast_unstable_v1) could not be written";
      }
      return "KWin does not offer its screencast protocol to Polaris. On KDE Plasma this usually means KWin "
             "has not picked up Polaris's permission entry yet; it will on the next try";
    }
  }  // namespace

  probe_t probe() {
    const auto permission = kwingrab::ensure_screencast_permission();
    const auto connection = connect(false, permission == kwingrab::permission_e::written);
    if (!connection) {
      return {.available = false, .version = 0, .reason = "Polaris cannot connect to the Wayland display"};
    }
    const auto version = connection->screencast_version;
    if (version == 0) {
      return {.available = false, .version = 0, .reason = missing_protocol_reason(permission)};
    }
    if (!virtual_display::kwin_screencast_version_supported(version)) {
      return {
        .available = false,
        .version = version,
        .reason = "KWin offers screencast version " + std::to_string(version) +
                  ", and creating a screen needs version 4 (KDE Plasma 6)",
      };
    }
    return {.available = true, .version = version, .reason = {}};
  }

  std::optional<std::vector<std::string>> output_names() {
    connection_t connection {false};
    if (!connection.open()) {
      return std::nullopt;
    }
    return connection.names();
  }

  std::optional<created_t> create(const std::string &request_name, int width, int height, std::string &error) {
    const auto permission = kwingrab::ensure_screencast_permission();
    auto anchor = std::make_unique<anchor_t>();
    anchor->connection = connect(true, permission == kwingrab::permission_e::written);
    if (!anchor->connection) {
      error = "cannot connect to the Wayland display";
      return std::nullopt;
    }
    auto &connection = *anchor->connection;
    if (!connection.screencast) {
      error = missing_protocol_reason(permission);
      return std::nullopt;
    }
    if (!virtual_display::kwin_screencast_version_supported(connection.screencast_version)) {
      error = "KWin offers screencast version " + std::to_string(connection.screencast_version) +
              ", and creating a screen needs version 4";
      return std::nullopt;
    }

    const auto expected = virtual_display::kwin_output_expected_name(request_name);
    if (connection.find(expected)) {
      error = "KWin already has an output named [" + expected + "]";
      return std::nullopt;
    }
    const auto globals_before = connection.output_globals();

    anchor->output_name = expected;
    anchor->stream = zkde_screencast_unstable_v1_stream_virtual_output_with_description(
      connection.screencast,
      request_name.c_str(),
      output_description,
      width,
      height,
      wl_fixed_from_double(1.0),
      ZKDE_SCREENCAST_UNSTABLE_V1_POINTER_HIDDEN
    );
    zkde_screencast_stream_unstable_v1_add_listener(anchor->stream, &anchor_t::stream_listener, anchor.get());

    // The output is ours only when it is a global that did not exist before the
    // request and carries exactly the name asked for. A name match alone could
    // be an output someone else already had.
    const output_t *proven = nullptr;
    const auto deadline = std::chrono::steady_clock::now() + stream_deadline;
    while (std::chrono::steady_clock::now() < deadline && !anchor->failed) {
      const auto *output = connection.find(expected);
      if (anchor->created && output && !globals_before.contains(output->global) &&
          output->width > 0 && output->height > 0) {
        proven = output;
        break;
      }
      if (!connection.pump(50ms)) {
        error = "lost the connection to KWin while it created the output";
        return std::nullopt;
      }
    }
    if (anchor->failed) {
      error = "KWin refused to create the output: " + anchor->failure;
      return std::nullopt;
    }
    if (!proven) {
      error = "KWin did not publish [" + expected + "] as a new output within 5 s";
      return std::nullopt;
    }

    created_t result {.output_name = expected, .width = proven->width, .height = proven->height};
    if (!anchor->start_reader()) {
      error = "could not start the thread that keeps the connection to KWin read";
      return std::nullopt;
    }
    {
      std::lock_guard lock {anchors_mutex};
      anchors[expected] = std::move(anchor);
    }
    BOOST_LOG(info) << "KWin virtual output: created ["sv << result.output_name << "] "sv
                    << result.width << "x"sv << result.height;
    return result;
  }

  bool anchored(const std::string &output_name) {
    std::lock_guard lock {anchors_mutex};
    return anchors.contains(output_name);
  }

  namespace {
    constexpr int dbus_timeout_ms = 5000;

    std::filesystem::path follow_script_path(const std::string &output_name) {
      const char *runtime = std::getenv("XDG_RUNTIME_DIR");
      const std::filesystem::path directory = runtime && *runtime ? runtime : "/tmp";
      return directory / ("polaris-" + virtual_display::kwin_window_follow_plugin_name(output_name) + ".js");
    }

    /** One call to KWin's scripting interface; nullptr and `error` set on failure. */
    GVariant *call_scripting(const char *method, GVariant *arguments, const GVariantType *reply, std::string &error) {
      GError *failure = nullptr;
      GDBusConnection *bus = g_bus_get_sync(G_BUS_TYPE_SESSION, nullptr, &failure);
      if (!bus) {
        error = std::string {"no session bus: "} + (failure ? failure->message : "unknown");
        if (failure) {
          g_error_free(failure);
        }
        if (arguments) {
          g_variant_unref(g_variant_ref_sink(arguments));
        }
        return nullptr;
      }
      GVariant *result = g_dbus_connection_call_sync(
        bus, "org.kde.KWin", "/Scripting", "org.kde.kwin.Scripting", method,
        arguments, reply, G_DBUS_CALL_FLAGS_NONE, dbus_timeout_ms, nullptr, &failure
      );
      g_object_unref(bus);
      if (!result) {
        error = std::string {"KWin scripting "} + method + " failed: " + (failure ? failure->message : "unknown");
        if (failure) {
          g_error_free(failure);
        }
      }
      return result;
    }

    void unload_follow_script(const std::string &plugin) {
      std::string ignored;
      if (GVariant *result = call_scripting("unloadScript", g_variant_new("(s)", plugin.c_str()), G_VARIANT_TYPE("(b)"), ignored)) {
        g_variant_unref(result);
      }
    }
  }  // namespace

  bool follow_windows(const std::string &output_name, std::string &error) {
    const auto plugin = virtual_display::kwin_window_follow_plugin_name(output_name);
    const auto path = follow_script_path(output_name);
    {
      std::ofstream out(path, std::ios::trunc);
      if (!out) {
        error = "could not write " + path.string();
        return false;
      }
      out << virtual_display::kwin_window_follow_script(output_name);
    }
    ::chmod(path.c_str(), S_IRUSR | S_IWUSR);

    // A copy left by a Polaris that stopped without unloading it would keep its
    // own handler; replace it rather than run two.
    unload_follow_script(plugin);
    GVariant *loaded = call_scripting(
      "loadScript", g_variant_new("(ss)", path.c_str(), plugin.c_str()), G_VARIANT_TYPE("(i)"), error
    );
    if (!loaded) {
      return false;
    }
    gint32 id = -1;
    g_variant_get(loaded, "(i)", &id);
    g_variant_unref(loaded);
    if (id < 0) {
      error = "KWin refused the window script";
      return false;
    }
    // start() runs every loaded script that is not running yet.
    GVariant *started = call_scripting("start", nullptr, nullptr, error);
    if (!started) {
      unload_follow_script(plugin);
      return false;
    }
    g_variant_unref(started);
    BOOST_LOG(info) << "KWin virtual output: new windows follow ["sv << output_name << "] while it exists"sv;
    return true;
  }

  void stop_following_windows(const std::string &output_name) {
    unload_follow_script(virtual_display::kwin_window_follow_plugin_name(output_name));
    std::error_code ignored;
    std::filesystem::remove(follow_script_path(output_name), ignored);
  }

  bool release(const std::string &output_name, std::chrono::milliseconds budget) {
    std::unique_ptr<anchor_t> anchor;
    {
      std::lock_guard lock {anchors_mutex};
      if (auto node = anchors.extract(output_name)) {
        anchor = std::move(node.mapped());
      }
    }
    if (anchor) {
      if (anchor->dead || anchor->closed) {
        BOOST_LOG(info) << "KWin virtual output: the stream holding ["sv << output_name
                        << "] had already been "sv << (anchor->dead ? "disconnected"sv : "closed by KWin"sv);
      }
      // Stop reading before touching the connection from this thread, then
      // close the stream; dropping the anchor disconnects, which removes the
      // output even if KWin missed the close.
      anchor->stop_reader();
      anchor->close_stream();
      anchor.reset();
    }

    connection_t verify {false};
    if (!verify.open()) {
      BOOST_LOG(error) << "KWin virtual output: cannot connect to verify that ["sv << output_name << "] is gone"sv;
      return false;
    }
    const auto deadline = std::chrono::steady_clock::now() + budget;
    std::optional<std::chrono::steady_clock::time_point> absent_since;
    do {
      const auto now = std::chrono::steady_clock::now();
      if (!verify.find(output_name)) {
        if (!absent_since) {
          absent_since = now;
        }
        if (now - *absent_since >= stable_absence) {
          BOOST_LOG(info) << "KWin virtual output: removal of ["sv << output_name << "] verified"sv;
          return true;
        }
      } else {
        absent_since.reset();
      }
      if (!verify.pump(50ms)) {
        BOOST_LOG(error) << "KWin virtual output: lost the connection while verifying ["sv << output_name << "] is gone"sv;
        return false;
      }
    } while (std::chrono::steady_clock::now() < deadline);

    BOOST_LOG(error) << "KWin virtual output: ["sv << output_name << "] is still present after releasing it"sv;
    return false;
  }

}  // namespace kwin_virtual_output
