/**
 * @file src/platform/linux/kwingrab.cpp
 * @brief KWin zkde_screencast_unstable_v1 → PipeWire node (Sunshine pattern, no .cpp include).
 *
 * After node exists, portal_grab feeds pipewire_capture the same way as gamescopegrab
 * (remote_fd=-1, local graph). Portal remains fallback when protocol/permission missing.
 */

#include "kwingrab.h"

#include "src/logging.h"

#include <algorithm>
#include <chrono>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <map>
#include <memory>
#include <poll.h>
#include <pwd.h>
#include <string>
#include <system_error>
#include <thread>
#include <unistd.h>
#include <vector>
#include <wayland-client.h>

// Generated by cmake GEN_WAYLAND from src/platform/linux/protocols/
#include "zkde-screencast-unstable-v1.h"

using namespace std::literals;

namespace kwingrab {
  namespace {

    constexpr const char *k_desktop_prefix = "dev.polaris-stream.app.Polaris.kwin";

    std::string executable_path() {
      char buf[4096];
      const ssize_t n = readlink("/proc/self/exe", buf, sizeof(buf) - 1);
      if (n <= 0) {
        return {};
      }
      buf[n] = '\0';
      return buf;
    }

    std::string xdg_data_home() {
      if (const char *d = std::getenv("XDG_DATA_HOME"); d && *d) {
        return d;
      }
      if (const char *h = std::getenv("HOME"); h && *h) {
        return std::string(h) + "/.local/share";
      }
      if (auto *pw = getpwuid(geteuid()); pw && pw->pw_dir) {
        return std::string(pw->pw_dir) + "/.local/share";
      }
      return {};
    }

    std::string desktop_exec_line(const std::string &path) {
      std::ifstream in(path);
      std::string line;
      while (std::getline(in, line)) {
        if (line.rfind("Exec=", 0) == 0 && line.size() > 5) {
          return line.substr(5);
        }
      }
      return {};
    }

    bool system_permission_present(const std::string &exe) {
      std::vector<std::string> dirs;
      if (const char *e = std::getenv("XDG_DATA_DIRS"); e && *e) {
        std::string s {e};
        std::size_t start = 0;
        while (start <= s.size()) {
          const auto end = s.find(':', start);
          auto dir = s.substr(start, end == std::string::npos ? std::string::npos : end - start);
          if (!dir.empty()) {
            dirs.push_back(std::move(dir));
          }
          if (end == std::string::npos) {
            break;
          }
          start = end + 1;
        }
      }
      if (dirs.empty()) {
        dirs = {"/usr/local/share", "/usr/share"};
      }
      for (const auto &dir : dirs) {
        const auto path = dir + "/applications/" + k_desktop_prefix + ".desktop";
        if (std::filesystem::exists(path) && desktop_exec_line(path) == exe) {
          BOOST_LOG(info) << "kwingrab: system permission desktop "sv << path;
          return true;
        }
      }
      return false;
    }

    /**
     * KWin requires a .desktop with X-KDE-Wayland-Interfaces=zkde_screencast_unstable_v1
     * matching this binary. Create a user-local one when missing (Sunshine pattern).
     */
    void ensure_screencast_permission() {
      if (const char *no = std::getenv("KWIN_WAYLAND_NO_PERMISSION_CHECKS"); no && std::string(no) == "1") {
        BOOST_LOG(info) << "kwingrab: KWIN_WAYLAND_NO_PERMISSION_CHECKS=1; skip desktop permission"sv;
        return;
      }
      const auto exe = executable_path();
      if (exe.empty()) {
        return;
      }
      if (system_permission_present(exe)) {
        return;
      }
      const auto data = xdg_data_home();
      if (data.empty()) {
        return;
      }
      const auto apps = std::filesystem::path(data) / "applications";
      std::error_code ec;
      std::filesystem::create_directories(apps, ec);
      // Reuse an existing matching user desktop if present.
      for (const auto &entry : std::filesystem::directory_iterator(apps, ec)) {
        if (ec) {
          break;
        }
        const auto name = entry.path().filename().string();
        if (name.rfind(k_desktop_prefix, 0) != 0 || !name.ends_with(".desktop")) {
          continue;
        }
        if (desktop_exec_line(entry.path().string()) == exe) {
          BOOST_LOG(debug) << "kwingrab: reuse user permission desktop "sv << entry.path().string();
          return;
        }
      }
      const auto stamp = std::chrono::system_clock::now().time_since_epoch().count();
      const auto path = apps / (std::string(k_desktop_prefix) + "." + std::to_string(stamp) + ".desktop");
      std::ofstream out(path);
      if (!out) {
        BOOST_LOG(warning) << "kwingrab: failed to write permission desktop "sv << path.string();
        return;
      }
      out << "[Desktop Entry]\n"
          << "Exec=" << exe << '\n'
          << "X-KDE-Wayland-Interfaces=zkde_screencast_unstable_v1\n"
          << "Type=Application\n"
          << "Name=Polaris KWin screencast permission\n"
          << "Comment=Polaris host capture without xdg-desktop-portal picker\n"
          << "NoDisplay=true\n";
      out.close();
      BOOST_LOG(info) << "kwingrab: wrote permission desktop "sv << path.string()
                      << "; waiting 1s for KWin to notice"sv;
      std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    }

    struct output_param_t {
      std::string name;
      int width = 0;
      int height = 0;
    };

    class screencast_t {
    public:
      ~screencast_t() {
        if (stream_) {
          zkde_screencast_stream_unstable_v1_close(stream_);
          stream_ = nullptr;
        }
        if (screencast_) {
          zkde_screencast_unstable_v1_destroy(screencast_);
          screencast_ = nullptr;
        }
        for (auto &[output, _] : outputs_) {
          wl_output_destroy(output);
        }
        outputs_.clear();
        if (registry_) {
          wl_registry_destroy(registry_);
          registry_ = nullptr;
        }
        if (display_) {
          wl_display_disconnect(display_);
          display_ = nullptr;
        }
      }

      int init(bool setup_permissions) {
        if (setup_permissions) {
          ensure_screencast_permission();
        }
        const char *wl_name = std::getenv("WAYLAND_DISPLAY");
        if (!wl_name || !*wl_name) {
          BOOST_LOG(debug) << "kwingrab: WAYLAND_DISPLAY not set"sv;
          return -1;
        }
        display_ = wl_display_connect(wl_name);
        if (!display_) {
          BOOST_LOG(debug) << "kwingrab: cannot connect Wayland display "sv << wl_name;
          return -1;
        }
        registry_ = wl_display_get_registry(display_);
        wl_registry_add_listener(registry_, &registry_listener, this);
        wl_display_roundtrip(display_);
        wl_display_roundtrip(display_);
        return 0;
      }

      bool has_screencast() const {
        return screencast_ != nullptr;
      }

      int start(std::string_view output_name) {
        if (outputs_.empty()) {
          BOOST_LOG(warning) << "kwingrab: no wl_output"sv;
          return -1;
        }
        struct wl_output *output = nullptr;
        std::shared_ptr<output_param_t> params;
        if (!output_name.empty()) {
          for (const auto &[o, p] : outputs_) {
            if (p->name == output_name) {
              output = o;
              params = p;
              break;
            }
          }
          if (!output) {
            BOOST_LOG(error) << "kwingrab: requested output ["sv << output_name
                             << "] not found; refusing another output"sv;
            if (!output_selection_can_fallback(output_name)) {
              return -1;
            }
          }
        }
        if (!output) {
          output = outputs_.begin()->first;
          params = outputs_.begin()->second;
        }
        if (!screencast_) {
          BOOST_LOG(info) << "kwingrab: zkde_screencast_unstable_v1 not in registry "
                             "(not KWin, or missing X-KDE-Wayland-Interfaces desktop)"sv;
          return -1;
        }
        stream_ = zkde_screencast_unstable_v1_stream_output(
          screencast_,
          output,
          ZKDE_SCREENCAST_UNSTABLE_V1_POINTER_EMBEDDED
        );
        zkde_screencast_stream_unstable_v1_add_listener(stream_, &stream_listener, this);
        if (wait_for_stream() < 0) {
          return -1;
        }
        if (stream_failed_) {
          BOOST_LOG(warning) << "kwingrab: stream failed: "sv << stream_error_;
          return -1;
        }
        if (node_id_ == 0 && object_serial_ == 0) {
          BOOST_LOG(warning) << "kwingrab: timeout waiting for created/serial"sv;
          return -1;
        }
        if (!params || params->width <= 0 || params->height <= 0) {
          BOOST_LOG(warning) << "kwingrab: missing output dimensions"sv;
          return -1;
        }
        source_.node_id = node_id_;
        source_.object_serial = object_serial_;
        source_.width = params->width;
        source_.height = params->height;
        source_.output_name = params->name;
        BOOST_LOG(info) << "kwingrab: stream ready node="sv << source_.node_id
                        << " serial="sv << source_.object_serial
                        << " output="sv << source_.output_name
                        << " "sv << source_.width << "x"sv << source_.height
                        << " (no portal picker; HDR depends on KWin export)"sv;
        return 0;
      }

      stream_source_t source_;

    private:
      wl_display *display_ = nullptr;
      wl_registry *registry_ = nullptr;
      zkde_screencast_unstable_v1 *screencast_ = nullptr;
      zkde_screencast_stream_unstable_v1 *stream_ = nullptr;
      std::map<wl_output *, std::shared_ptr<output_param_t>> outputs_;
      bool stream_failed_ = false;
      bool stream_ready_ = false;
      std::string stream_error_;
      std::uint32_t node_id_ = 0;
      std::uint64_t object_serial_ = 0;

      int wait_for_stream() {
        const auto deadline = std::chrono::steady_clock::now() + std::chrono::seconds(5);
        while (!stream_ready_ && !stream_failed_ && std::chrono::steady_clock::now() < deadline) {
          wl_display_flush(display_);
          pollfd pfd {};
          pfd.fd = wl_display_get_fd(display_);
          pfd.events = POLLIN;
          const auto remaining = std::chrono::duration_cast<std::chrono::milliseconds>(
            deadline - std::chrono::steady_clock::now()
          );
          if (remaining.count() <= 0) {
            break;
          }
          if (poll(&pfd, 1, static_cast<int>(remaining.count())) > 0 && (pfd.revents & POLLIN)) {
            if (wl_display_dispatch(display_) < 0) {
              BOOST_LOG(warning) << "kwingrab: wl_display_dispatch failed"sv;
              return -1;
            }
          }
        }
        return 0;
      }

      static void on_registry_global(
        void *data,
        wl_registry *reg,
        std::uint32_t name,
        const char *interface,
        std::uint32_t version
      ) {
        auto *self = static_cast<screencast_t *>(data);
        if (!std::strcmp(interface, zkde_screencast_unstable_v1_interface.name)) {
          const auto ver = std::min(version, 6u);
          self->screencast_ = static_cast<zkde_screencast_unstable_v1 *>(
            wl_registry_bind(reg, name, &zkde_screencast_unstable_v1_interface, ver)
          );
          BOOST_LOG(debug) << "kwingrab: bound zkde_screencast_unstable_v1 v"sv << ver;
        }
        else if (!std::strcmp(interface, wl_output_interface.name)) {
          const auto ver = std::min(version, 4u);
          auto *output = static_cast<wl_output *>(
            wl_registry_bind(reg, name, &wl_output_interface, ver)
          );
          auto [it, inserted] = self->outputs_.try_emplace(output, std::make_shared<output_param_t>());
          if (inserted) {
            wl_output_add_listener(output, &output_listener, self);
          }
          else {
            wl_output_destroy(output);
          }
        }
      }

      static void on_registry_global_remove(void *, wl_registry *, std::uint32_t) {
      }

      static constexpr wl_registry_listener registry_listener = {
        .global = on_registry_global,
        .global_remove = on_registry_global_remove,
      };

      static void on_output_geometry(
        void *,
        wl_output *,
        std::int32_t,
        std::int32_t,
        std::int32_t,
        std::int32_t,
        std::int32_t,
        const char *,
        const char *,
        std::int32_t
      ) {
      }

      static void on_output_mode(
        void *data,
        wl_output *output,
        std::uint32_t flags,
        std::int32_t width,
        std::int32_t height,
        std::int32_t
      ) {
        if (!(flags & WL_OUTPUT_MODE_CURRENT)) {
          return;
        }
        auto *self = static_cast<screencast_t *>(data);
        auto it = self->outputs_.find(output);
        if (it != self->outputs_.end()) {
          it->second->width = width;
          it->second->height = height;
        }
      }

      static void on_output_done(void *, wl_output *) {
      }

      static void on_output_scale(void *, wl_output *, std::int32_t) {
      }

      static void on_output_name(void *data, wl_output *output, const char *name) {
        auto *self = static_cast<screencast_t *>(data);
        auto it = self->outputs_.find(output);
        if (it != self->outputs_.end() && name) {
          it->second->name = name;
        }
      }

      static void on_output_description(void *, wl_output *, const char *) {
      }

      static constexpr wl_output_listener output_listener = {
        .geometry = on_output_geometry,
        .mode = on_output_mode,
        .done = on_output_done,
        .scale = on_output_scale,
        .name = on_output_name,
        .description = on_output_description,
      };

      static void on_stream_closed(void *data, zkde_screencast_stream_unstable_v1 *) {
        auto *self = static_cast<screencast_t *>(data);
        BOOST_LOG(warning) << "kwingrab: stream closed by compositor"sv;
        self->stream_ready_ = false;
        self->stream_error_ = "stream closed by server";
      }

      static void on_stream_created(void *data, zkde_screencast_stream_unstable_v1 *, std::uint32_t node) {
        auto *self = static_cast<screencast_t *>(data);
        self->node_id_ = node;
        self->stream_failed_ = false;
        self->stream_ready_ = true;
      }

      static void on_stream_failed(void *data, zkde_screencast_stream_unstable_v1 *, const char *err) {
        auto *self = static_cast<screencast_t *>(data);
        self->stream_failed_ = true;
        self->stream_ready_ = false;
        self->stream_error_ = err ? err : "unknown";
      }

      static void on_stream_serial(
        void *data,
        zkde_screencast_stream_unstable_v1 *,
        std::uint32_t hi,
        std::uint32_t lo
      ) {
        auto *self = static_cast<screencast_t *>(data);
        self->object_serial_ = (static_cast<std::uint64_t>(hi) << 32) | lo;
      }

      static constexpr zkde_screencast_stream_unstable_v1_listener stream_listener = {
        .closed = on_stream_closed,
        .created = on_stream_created,
        .failed = on_stream_failed,
        .serial = on_stream_serial,
      };
    };

  }  // namespace

  struct session_t::impl_t {
    std::unique_ptr<screencast_t> cast;
  };

  session_t::session_t():
      impl_(std::make_unique<impl_t>()) {
  }

  session_t::~session_t() = default;

  session_t::session_t(session_t &&) noexcept = default;
  session_t &session_t::operator=(session_t &&) noexcept = default;

  bool session_t::valid() const {
    if (!impl_ || !impl_->cast) {
      return false;
    }
    const auto &s = impl_->cast->source_;
    return s.node_id != 0 || s.object_serial != 0;
  }

  const stream_source_t &session_t::source() const {
    static const stream_source_t empty {};
    if (!impl_ || !impl_->cast) {
      return empty;
    }
    return impl_->cast->source_;
  }

  bool output_selection_can_fallback(std::string_view requested_output_name) {
    return requested_output_name.empty();
  }

  std::unique_ptr<session_t> start_output_session(std::string_view output_name) {
    auto session = std::make_unique<session_t>();
    session->impl_->cast = std::make_unique<screencast_t>();
    if (session->impl_->cast->init(true) < 0) {
      return nullptr;
    }
    if (!session->impl_->cast->has_screencast()) {
      BOOST_LOG(info) << "kwingrab: screencast protocol unavailable; portal remains fallback"sv;
      return nullptr;
    }
    if (session->impl_->cast->start(output_name) < 0) {
      return nullptr;
    }
    return session;
  }

  bool prefer_for_generation(const capture_generation::identity_t &generation) {
    const auto &mode = generation.stream_mode;
    // Host KDE paths only. gamescope_stream / labwc private runtimes stay on
    // gamescopegrab / portal / wlroots — never kwingrab.
    if (mode == "desktop_display" || mode == "headless_dongle" ||
        mode == "host_virtual_display") {
      return true;
    }
    // Empty mode historically maps to desktop-ish host on some configs; only
    // when the immutable generation did not select a private runtime.
    if (mode.empty() &&
        !generation.use_cage_compositor &&
        generation.private_runtime != "gamescope" &&
        generation.private_runtime != "labwc") {
      return true;
    }
    return false;
  }

  bool require_for_generation(const capture_generation::identity_t &generation) {
    return generation.stream_mode == "host_virtual_display";
  }

}  // namespace kwingrab
