/**
 * @file src/platform/linux/private_session_input.h
 * @brief Input configuration for the private labwc session.
 *
 * The private session and the host desktop session can be alive at the same
 * time. When the private compositor is started with a libinput backend it opens
 * every physical input device on the seat, so the keyboard and mouse on the desk
 * drive the streamed session as well as the desktop in front of the user.
 *
 * Polaris owns the private session's rc.xml, so it can tell labwc to ignore the
 * host's physical devices while leaving the virtual devices Polaris creates for
 * the client enabled. The opposite direction — Polaris' virtual devices leaking
 * into the host session — is handled by seat isolation, see
 * input/input_seat_isolation.h.
 */
#pragma once

#include <filesystem>
#include <string>
#include <string_view>
#include <vector>

namespace platf::private_session_input {

  /// A physical input device present on the host.
  struct input_device_t {
    std::string name;
    std::string sysfs_path;
  };

  /// Header written at the top of every generated rc.xml.
  constexpr std::string_view generated_marker = "<!-- Generated by Polaris. Edits are overwritten.";

  /**
   * @brief Whether a device name belongs to a Polaris virtual input device.
   *
   * Those must never be ignored: they are how the client's input reaches the
   * private session in the first place.
   */
  bool is_polaris_virtual_device(std::string_view name);

  /// Read the host's input devices from /sys/class/input.
  std::vector<input_device_t> enumerate_host_input_devices();

  /**
   * @brief Build the labwc <libinput> block that ignores the host's devices.
   * @param devices Devices seen on the host, Polaris' own included.
   * @return XML block, empty when there is nothing to ignore.
   */
  std::string build_libinput_isolation_block(const std::vector<input_device_t> &devices);

  /// Build the full kiosk rc.xml for the private session.
  std::string build_rc_xml(const std::vector<input_device_t> &devices);

  /**
   * @brief Write the generated rc.xml into the private session's config dir.
   *
   * A file Polaris did not generate is left untouched: an rc.xml without the
   * generated marker is a user's own configuration.
   *
   * @param config_dir Directory passed to labwc with -C.
   * @param devices Devices seen on the host.
   * @param status_out Human readable outcome, for the log.
   * @return true when the private session's rc.xml is the generated one.
   */
  bool ensure_generated_rc_xml(
    const std::filesystem::path &config_dir,
    const std::vector<input_device_t> &devices,
    std::string &status_out
  );

}  // namespace platf::private_session_input
